Repository seek4science/seek, pull requests merged in 2023-07, with the labels that each got.

#1518 Remove the not selected option from filtered template form
  app/assets/javascripts/templates.js
Labels: datahub

#1517 Fix paste from clipboard in single page
  app/assets/javascripts/single_page/dynamic_table.js.erb
  config/help_links.yml
Labels: bug, datahub

#1543 Update roles.md
  help/user-guide/bulk-change-sharing-permission.md
  help/user-guide/general-attributes.md
  help/user-guide/index.md
  help/user-guide/roles.md
  images/user-guide/bulk-permission-change/batch_sharing_publishing.png
  images/user-guide/gatekeeper_awaiting_approval.png
  images/user-guide/gatekeeper_gatekeeping.png
  images/user-guide/sharing_permissions.png
Labels: documentation

#1494 Describes gatekeeper expected functionality.
  help/user-guide/bulk-change-sharing-permission.md
  help/user-guide/general-attributes.md
  help/user-guide/index.md
  help/user-guide/roles.md
  images/user-guide/bulk-permission-change/batch_sharing_publishing.png
  images/user-guide/gatekeeper_awaiting_approval.png
  images/user-guide/gatekeeper_gatekeeping.png
  images/user-guide/sharing_permissions.png
Labels: documentation, gatekeeper
