Repository seek4science/seek, pull requests merged in 2024-01, with the labels that each got.

#1703 Share permission project list select2
  app/views/sharing/_group_permission_modal.html.erb
Labels: enhancement

#1707 Couple of small bugfixes
  app/assets/javascripts/single_page/dynamic_table.js.erb
  app/views/isa_assays/_form.html.erb
  app/views/single_pages/show.html.erb
  lib/seek/isa_templates/template_attributes_schema.json
Labels: bug, datahub

#1716 Add rake upgrade task for recognising ISA JSON compliant investigations
  lib/tasks/seek_upgrades.rake
Labels: bug, datahub

#1717 Fix rake task
  lib/tasks/seek_upgrades.rake
Labels: bug

#1704 Issue 1701 fix controlled vocabs in template attributes
  app/assets/javascripts/single_page/dynamic_table.js.erb
  app/assets/javascripts/single_page/index.js.erb
  app/assets/javascripts/templates.js
  app/controllers/single_pages_controller.rb
  app/controllers/templates_controller.rb
  app/helpers/dynamic_table_helper.rb
  app/helpers/templates_helper.rb
  app/models/template.rb
  app/models/template_attribute.rb
  app/views/isa_studies/_sample_types_form.html.erb
  app/views/isa_studies/new.html.erb
  app/views/sample_types/_sample_attribute_form.html.erb
  app/views/single_pages/_duplicate_samples_panel.html.erb
  app/views/single_pages/_new_samples_panel.html.erb
  app/views/single_pages/_update_samples_panel.html.erb
  app/views/single_pages/sample_upload_content.html.erb
  app/views/templates/_template_attribute_form.html.erb
  app/views/templates/edit.html.erb
  app/views/templates/new.html.erb
  db/migrate/20231218133053_add_linked_sample_type_to_templates.rb
  db/schema.rb
Labels: bug, datahub

#1725 Fix dynamic table in default view
  app/assets/javascripts/single_page/dynamic_table.js.erb
  app/views/isa_assays/_assay_design.html.erb
  app/views/isa_studies/_study_design.html.erb
  app/views/single_pages/show.html.erb
Labels: bug, datahub
